# Generated by Django 3.2.12 on 2022-04-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='google_link',
            field=models.CharField(default='sanjay', max_length=255),
        ),
    ]
