# Generated by Django 3.2.12 on 2022-04-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20220403_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('code', 'code'), ('mobile_review', 'mobile_review'), ('content', 'content'), ('comedy', 'comedy'), ('gaming', 'gaming'), ('film_review', 'film_review'), ('cooking', 'cooking')], max_length=255),
        ),
    ]
